### ISSUE TITLE
Remove API Key from code

### ISSUE THREAD

**Issue by shrayasr** [davidpdrsn/Ten-Moves#54]
https://github.com/davidpdrsn/Ten-Moves/blob/master/TenMoves/API.m#L38 seems to have the API key. Wouldn't it be better for this to be in a config file?

**Comment by davidpdrsn** [comment]
Ah thanks! I just open sourced the repo to help people on SO with my
question.

On Wed, Jul 29, 2015 at 6:28 AM, Shrayas Rajagopal <notifications@github.com

**Comment by shrayasr** [comment]
Ah. If you're going to make it closed, then its OK if you just regenerate the key :+1:

Btw, fellow flourisher :)
